apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  namespace: movies-app
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway:7.7.0
          args:
            - info
            - repair
            - migrate
            - info
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: FLYWAY_USER
              value: postgres
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: FLYWAY_GROUP
              value: "true"
          volumeMounts:
            - mountPath: /flyway/sql
              name: sql
      volumes:
        - name: sql
          configMap:
            name: migration-config
      restartPolicy: Never
