apiVersion: v1
kind: Service
metadata:
  name: movies-front-service
  namespace: movies-app
  labels:
    app: movies-front
spec:
  type: LoadBalancer
  selector:
    app: movies-front
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 32000
