apiVersion: v1
kind: Service
metadata:
  name: movies-api-service
  namespace: movies-app
  labels:
    app: movies-api
spec:
  type: NodePort
  selector:
    app: movies-api
  ports:
    - protocol: TCP
      name: movies-api
      port: 8000
      targetPort: http-movies-api
      nodePort: 31000
