apiVersion: v1
kind: Service
metadata:
  name: movies-front-service
  namespace: movies-app
  labels:
    app: movies-front
spec:
  type: NodePort
  selector:
    app: movies-front
  ports:
    - protocol: TCP
      name: movies-front
      port: 80
      targetPort: http-movies-front 
      nodePort: 32000
